### PR TITLE
Fix content size issue on macOS

### LINKED ISSUE #87: NSCollectionView does not update the content size correctly after animating layout changes
When setting a new layout the contentSize doesn't correctly update, this can be seen in the macOS example project when switching between the horizontal layout -> mosaic layout. As the previous content size has a larger width than the updated layout. Resizing the window makes the collection view update correctly but I am not sure at this time what is causing this.

This may also be an issue on iOS but as the collections views content size doesn't change like it does on macOS it's not noticeable.

### PR DESCRIPTION
**Pull request by zenangst**
This adds a "horrible" hack to get the content size to update on macOS when transitioning between layouts. It will temporarily resize the window to make sure that the scroll view's document view gets a new size.

Fixes #87

- Enables `InjectionIII` for the macOS demo

### CODE REVIEW

File: Sources/macOS/Extensions/BlueprintLayout+macOS.swift [hunk 1]
```diff
@@ -45,6 +46,28 @@ extension BlueprintLayout {
...
+      CATransaction.begin()
+      CATransaction.setDisableActions(true)
+      CATransaction.setAnimationDuration(0.0)
+      let originalFrame = window.frame
+      var frame = originalFrame
+      frame.origin.y = frame.origin.y - 0.025
+      frame.size.height = frame.size.height + 0.025
+      window.setFrame(frame, display: false)
+      CATransaction.commit()
+      DispatchQueue.main.asyncAfter(deadline: .now() + 0.045) {
```
Comment (zenangst) [inline Sources/macOS/Extensions/BlueprintLayout+macOS.swift]: The values used are not very scientific, it is just what I used that gained the best results when testing.
